if (WIN32)
    set(evildragon_OS_WIN ON)
elseif (APPLE)
    set(evildragon_OS_APPLE ON)

    if (IOS OR CMAKE_SYSTEM_NAME STREQUAL iOS)
        set(evildragon_OS_IOS ON)
    else()
        set(evildragon_OS_MACOS ON)
    endif()
else()
    set(evildragon_OS_UNIX ON)

    if (ANDROID OR CMAKE_SYSTEM_NAME MATCHES "Android")
        set(evildragon_OS_ANDROID ON)
    elseif(CMAKE_SYSTEM_NAME MATCHES "Linux")
        set(evildragon_OS_LINUX ON)
    elseif(CMAKE_SYSTEM_NAME STREQUAL FreeBSD)
        set(evildragon_OS_FREEBSD ON)
    endif()
endif()


if (evildragon_OS_WIN)
    add_definitions(/DWIN32)
    add_definitions(/Devildragon_OS_WIN)
elseif(evildragon_OS_APPLE)
    add_definitions(/Devildragon_OS_APPLE)

    if (evildragon_OS_IOS)
        add_definitions(/Devildragon_OS_IOS)
    else()
        add_definitions(/Devildragon_OS_MACOS)
    endif()
elseif(evildragon_OS_UNIX)
    add_definitions(/Devildragon_OS_UNIX)

    if (evildragon_OS_ANDROID)
        add_definitions(/Devildragon_OS_ANDROID)
    elseif (evildragon_OS_LINUX)
        add_definitions(/Devildragon_OS_LINUX)
    elseif (evildragon_OS_FREEBSD)
        add_definitions(/Devildragon_OS_FREEBSD)
    endif()
endif()
